name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run simple test
      run: |
        uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        sleep 5
        curl -s http://127.0.0.1:8000/scan | grep '"status": "Scan successful"'

    - name: Build Docker Image
      run: |
        docker build -t code-inspector:latest .
